// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfzvwFeh5yfNds0XmAs7ImvsH8eogcj0I',
    appId: '1:643668187865:android:47c835dea769c86a34bcc8',
    messagingSenderId: '643668187865',
    projectId: 'fir-flutter-6c2d7',
    storageBucket: 'fir-flutter-6c2d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4WdTBPxjvlNxtfnSuzT6A6PL2bt8PkvY',
    appId: '1:643668187865:ios:7ba4061441e588ec34bcc8',
    messagingSenderId: '643668187865',
    projectId: 'fir-flutter-6c2d7',
    storageBucket: 'fir-flutter-6c2d7.appspot.com',
    androidClientId: '643668187865-a9q59gv90nv2oat1p2gaicpnlkt55384.apps.googleusercontent.com',
    iosClientId: '643668187865-e717nane7a6k4cdden5bi8jr1dlrpmfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );
}
